import {
  people01,
  people02,
  people03,
  facebook,
  instagram,
  linkedin,
  twitter,
  deliverycity,
  citydelivery2,
  catering,
  whatsapp,
  image01,
  image02,
  image03,
  image04,
  image05,
  image06,
  image07,
  image08,
  image09,
  image10,
  image11,
  image12,
  image13,
  image14,
  image15,
  image16,
  image17,
  image18,
  image19,
  image20,
  send,
  shield,
  star,
  arasli,
  azercell,
  avromed,
  arazsupermarket,
  agrico,
  avrora,
  avromak,
  aztrade,
  aqrokimya,
  azerimed,
  atsfood,
  azza,
  bakuinternationaltobacco,
  bolluq,
  cinemaplus,
  ersag,
  farmamedical,
  floraholland,
  florum,
  freshfruits,
  grandmart,
  growgroup,
  herbaflora,
  hommylife,
  konfiron,
  mazarina,
  mcdonalds,
  milla,
  oba,
  pepsico,
  sibirski,
  sosna,
  unityfood,
  vestprodukt,
  veyseloglu,
  zeytun,
  ziregulculuk,
} from "../assets";

export const features = [
  {
    id: "feature-1",
    icon: deliverycity,
    titleKey: "features.cityDelivery",
    contentKey: "features.cityDeliveryDesc",
  },
  {
    id: "feature-3",
    icon: citydelivery2,
    titleKey: "features.intercityDelivery",
    contentKey: "features.intercityDeliveryDesc",
  },
  {
    id: "feature-4",
    icon: catering,
    titleKey: "features.catering",
    contentKey: "features.cateringDesc",
  },
];

export const stats = [
  {
    id: "stats-1",
    titleKey: "stats.partners",
    value: "1000+",
  },
  {
    id: "stats-2",
    titleKey: "stats.expeditors",
    value: "50+",
  },
  {
    id: "stats-3",
    titleKey: "stats.deliveries",
    value: "15.000+",
  },
];

export const navLinks = [
  { id: "home", titleKey: "nav.home" },
  { id: "about", titleKey: "nav.about" },
  { id: "features", titleKey: "nav.services" },
  { id: "clients", titleKey: "nav.partners" },
  { id: "contact", titleKey: "nav.contact" },
];

export const socialMedia = [
  {
    id: "social-media-1",
    icon: instagram,
    link: "https://www.instagram.com/toofar.logistics/",
  },
  {
    id: "social-media-2",
    icon: facebook,
    link: "https://www.facebook.com/toofarlogistics",
  },
  {
    id: "social-media-3",
    icon: whatsapp,
    link: "whatsapp://send?text=Səhifəmizə nəzər yetirin: https://toofar/az",
  },
  {
    id: "social-media-4",
    icon: linkedin,
    link: "https://www.linkedin.com/",
  },
];

export const clients = [
  { id: "arasli", logo: arasli },
  { id: "arazsupermarket", logo: arazsupermarket },
  { id: "agrico", logo: agrico },
  { id: "avrora", logo: avrora },
  { id: "avromed", logo: avromed },
  { id: "azercell", logo: azercell },
  { id: "avromak", logo: avromak },
  { id: "aztrade", logo: aztrade },
  { id: "aqrokimya", logo: aqrokimya },
  { id: "azerimed", logo: azerimed },
  { id: "atsfood", logo: atsfood },
  { id: "azza", logo: azza },
  { id: "bakuinternationaltobacco", logo: bakuinternationaltobacco },
  { id: "bolluq", logo: bolluq },
  { id: "cinemaplus", logo: cinemaplus },
  { id: "ersag", logo: ersag },
  { id: "farmamedical", logo: farmamedical },
  { id: "floraholland", logo: floraholland },
  { id: "florum", logo: florum },
  { id: "freshfruits", logo: freshfruits },
  { id: "grandmart", logo: grandmart },
  { id: "growgroup", logo: growgroup },
  { id: "herbaflora", logo: herbaflora },
  { id: "hommylife", logo: hommylife },
  { id: "konfiron", logo: konfiron },
  { id: "mazarina", logo: mazarina },
  { id: "mcdonalds", logo: mcdonalds },
  { id: "milla", logo: milla },
  { id: "oba", logo: oba },
  { id: "pepsico", logo: pepsico },
  { id: "sibirski", logo: sibirski },
  { id: "sosna", logo: sosna },
  { id: "unityfood", logo: unityfood },
  { id: "vestprodukt", logo: vestprodukt },
  { id: "veyseloglu", logo: veyseloglu },
  { id: "zeytun", logo: zeytun },
  { id: "ziregulculuk", logo: ziregulculuk },
];

export const images = [
  { id: "image15", logo: image15 },
  { id: "image01", logo: image01 },
  { id: "image13", logo: image13 },
  { id: "image17", logo: image17 },
  { id: "image18", logo: image18 },
  { id: "image19", logo: image19 },
  { id: "image03", logo: image03 },
  { id: "image04", logo: image04 },
  { id: "image05", logo: image05 },
  { id: "image06", logo: image06 },
  { id: "image07", logo: image07 },
  { id: "image08", logo: image08 },
  { id: "image09", logo: image09 },
  { id: "image10", logo: image10 },
  { id: "image11", logo: image11 },
  { id: "image12", logo: image12 },
  { id: "image14", logo: image14 },
  { id: "image16", logo: image16 },
  { id: "image20", logo: image20 },
  { id: "image02", logo: image02 },
];
